# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01ceda1a7f260ff92e6f57cc395dd00356dbc23560b7cf22a7d5948fcbc34afa8eb79bddae20fe02678777d5a52a15eeacf55e695c8754ab75af1f2846b263d1

test:
  secret_key_base: 7aa04e4ab72bba78bd136596ff01f525c80c02f845a39cc2b652b3d71111adf0ba722a49eefe6bad1f3c7f2c1f2dca30b48e4b4739a9d2665261004982280f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
